services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
    restart: unless-stopped  
    networks:
      - palantir-net

  rabbitmq:
    image: rabbitmq:3.11-management    # официальное с management UI
    container_name: rabbitmq
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # HTTP‑UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      RABBITMQ_DEFAULT_USER:   $RABBITMQ_DEFAULT_USER     # ваш логин
      RABBITMQ_DEFAULT_PASS:   $RABBITMQ_DEFAULT_PASS     # ваш пароль
      RABBITMQ_DEFAULT_VHOST:  $RABBITMQ_DEFAULT_VHOST   # свой виртуальный хост
    restart: unless-stopped
    networks:
      - palantir-net

  logger:
    image: log-consumer-image:latest
    container_name: log-consumer
    depends_on:
      mongodb:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    restart: always
    networks:
      - palantir-net

  palantir-app:
    image: palantir-image:latest
    container_name: palantir-app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - palantir-net

  nuxt-app:
    image: palantir-frontend-image:latest
    container_name: palantir-frontend-app
    environment:
      NUXT_PUBLIC_API_BASE: http://palantir-app:8000
      NITRO_PORT: 3000
      NITRO_HOST: 0.0.0.0
    expose:
      - "3000"
    depends_on:
      - palantir-app
      - mongodb
    restart: unless-stopped
    networks:
      - palantir-net

  nginx-proxy:
    image: nginx:alpine
    container_name: palantir-nginx
    depends_on:
      - nuxt-app
      - palantir-app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /home/server/palantir_services/palantir/logs/nginx:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: unless-stopped
    networks:
      - palantir-net

volumes:
  rabbitmq_data:

networks:
  palantir-net:
    name: palantir-net
    driver: bridge
